#!/bin/bash
# Copyright 2026, Jamf Software LLC.
# This work is licensed under the terms of the Jamf Source Available License
# https://github.com/jamf/scripts/blob/main/LICENCE.md
# make-usage.sh: write docs/USAGE.md from every script's own --help, so the page cannot drift from the code.
# Run after changing any option:   bash admin/make-usage.sh
# Needs nothing but this repository: --help never contacts Jamf or Apple.
set -u
case "${1:-}" in -h|--help) /usr/bin/sed -n '2,/^set -u/p' "$0" | /usr/bin/sed -e '/^set -u/d' -e 's/^# \{0,1\}//'; exit 0;; esac
cd "$(dirname "$0")/.." || exit 1
OUT=docs/USAGE.md; mkdir -p docs
{
  echo "# Every script and its options"
  echo
  echo "Generated by \`admin/make-usage.sh\` from each script's own \`--help\`. Do not edit by hand."
  echo "Every script answers \`--help\` (or \`-h\`) and changes nothing when asked."
  for f in admin/readiness-check.py admin/preheat.sh admin/doctor.py admin/preheat-labels.py admin/sync-eas.py \
           admin/create-smart-groups.py admin/create-labels-policy.py admin/cache-collect.sh \
           admin/troubleshoot-server.sh admin/troubleshoot-client.sh admin/make-usage.sh; do
    echo; echo "## ${f#admin/}"; echo; echo '```'
    case "$f" in *.py) COLUMNS=100 /usr/bin/python3 "$f" --help;; *) /bin/bash "$f" --help;; esac
    echo '```'
  done
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
